
server:
  port: 8084


spring:
  application:
    name: scenario-factory
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: manager
    driver-class-name: oracle.jdbc.driver.OracleDriver


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
    show-sql: true
  cloud:
    loadbalancer:
      cache:
        ttl: 60s

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


