server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #can be switched to https for security
      defaultZone: http://${eureka.instance.hostname}:${server.port}