server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/LENOVO/Downloads/Internship\\ Content/fraudpaymentdetection/configrepo/
        bootstrap: true
  profiles:
    active: native
